[BE]: Sign in
Biniverse/server-test pull request #28
Opened 2024-09-20 06:11 UTC by stephenabv

# Pull Request: Implement User Login Functionality

## Description
This pull request introduces a new user login feature in our Express application. It includes the `loginUser` function, which handles login requests by validating the provided credentials against predefined constants.

## Changes Made
- Added the `loginUser` function to handle user login via username or email.
- Implemented validation logic to check credentials against hardcoded values.
- Included appropriate HTTP response status codes and messages for success and failure cases.

## Related Issues
- Closes #42 (User authentication feature)

## Type of Change
- [x] New Feature

## How to Test
1. Start the Express server.
2. Send a POST request to the `/login` endpoint with a JSON body containing either a `username` or `email`, along with `password` and an `app-key`.
3. Verify that valid credentials return a 200 status with a success message, while invalid credentials return a 401 status with an error message.

## Checklist
- [x] Code is written and works as expected.
- [x] Tests have been added or updated.
- [x] Documentation has been updated (if applicable).
- [x] Linting and formatting are consistent with project guidelines.

## Additional Notes
- This implementation uses hardcoded values for demonstration purposes. Consider implementing a database for user credentials in future updates.

2024-09-20 06:18 UTC, beefysalad commented
PR seems to be incomplete (current files changed is only 1) @stephenabv

2024-09-20 06:18 UTC, beefysalad commented
no docstrings as well

2024-09-20 06:20 UTC, beefysalad requested changes
Pls finish

2024-09-20 15:41 UTC, edzhabs commented
test

2024-09-20 15:41 UTC, edzhabs commented
> PR seems to be incomplete (current files changed is only 1) @stephenabv is still **on going?**

test

2024-09-20 15:43 UTC, edzhabs requested changes

2024-09-20 15:43 UTC, edzhabs commented on backend/src/routes/userRoutes.ts
>  userRouter.post("/users", createUser);
test

2024-09-20 15:43 UTC, beefysalad commented on backend/src/controller/loginController.ts
> +const APP_KEY = "A1b@2C#d4E$5f^6G*7h!8J9k(L)m0Nq";
what is the purpose of the app key @stephenabv

2024-09-20 15:43 UTC, beefysalad commented on backend/src/controller/loginController.ts
> +const APP_KEY = "A1b@2C#d4E$5f^6G*7h!8J9k(L)m0Nq";
normally when signing in, an auth middleware will generate a jwt containing the details of the user. is that what you are trying to simulate here?

2024-09-20 15:43 UTC, edzhabs commented on backend/src/routes/userRoutes.ts
>  userRouter.post("/users", createUser);
second test

2024-09-20 17:19 UTC, 22tofu commented on backend/src/service/loginService.ts
Why is this empty?

2024-09-20 17:19 UTC, 22tofu commented on backend/src/controller/loginController.ts
> +const APP_KEY = "A1b@2C#d4E$5f^6G*7h!8J9k(L)m0Nq";
test

2024-09-23 06:05 UTC, beefysalad requested changes

2024-09-23 06:05 UTC, beefysalad commented on backend/src/controller/loginController.ts
> +const APP_KEY = "A1b@2C#d4E$5f^6G*7h!8J9k(L)m0Nq";
instead of a hardcoded key, can we utilize jwt for this

2024-09-23 06:05 UTC, beefysalad commented on backend/src/controller/loginController.ts
> +    if (password !== PASSWORD) {
compare password with the one on the DB, this could also be hashed using argon

2024-09-23 06:05 UTC, beefysalad commented on backend/src/controller/loginController.ts
> +
add a db query to find using email or username?

2024-09-27 05:02 UTC, closed without merging