Feat/dashboard
Biniverse/server-test pull request #37
Opened 2024-09-23 10:31 UTC by essiee06

## Description

A background has been added, a header has been deleted, and a dashboard page has also been added, but it is not yet complete.

_Provide a description on what was changed/added/fixed in this PR_

## Checklist

_First, create a draft pull request. Then mark the PR as ready for review when all necessary checkbox items has been completed_

- [ ] Reviewed own code
- [ ] Commented on code that is hard to understand
- [ ] Implemented tests for the feature/bugfix
- [ ] All **_Required_** GitHub status checks pass
- [ ] The frontend and backend PR previews have been deployed

2024-09-23 10:45 UTC, beefysalad requested changes
will put a request for changes first since this is still an on going PR.

2024-09-23 12:16 UTC, 22tofu commented on frontend/src/components/Dashboard/index.tsx
> +  // flex flex-col items-start justify-start rounded-t-[15px] shadow-[1px_-1px_15px_0_rgba(34,34,34,0.83)] overflow-hidden bg-[var(--bricks-color-26b008)] h-[98vh] w-full
Please remove unused/commented code

2024-09-23 13:23 UTC, 22tofu commented on frontend/src/components/Dashboard/index.tsx
> +  // flex flex-col items-start justify-start rounded-t-[15px] shadow-[1px_-1px_15px_0_rgba(34,34,34,0.83)] overflow-hidden bg-[var(--bricks-color-26b008)] h-[98vh] w-full
Remove unused/commented code please

2024-09-23 13:24 UTC, essiee06 commented on frontend/src/components/Dashboard/index.tsx
> +  // flex flex-col items-start justify-start rounded-t-[15px] shadow-[1px_-1px_15px_0_rgba(34,34,34,0.83)] overflow-hidden bg-[var(--bricks-color-26b008)] h-[98vh] w-full
noted sir 22tofu

2024-09-24 04:37 UTC, edzhabs requested changes

2024-09-24 04:37 UTC, edzhabs commented on frontend/src/components/Dashboard/index.tsx
> +        <div
can these specific colors be move to tailwind config theme so that it is reusable and can be changed easily in the future?
`var(--bricks-color-26b008)`
`rgba(34,34,34,0.83)`
_sample in Chatgpt_
![image](https://github.com/user-attachments/assets/fb52020b-1e29-434b-a9e3-1b8619403699)

div
`<div className="flex flex-col items-start justify-start overflow-hidden rounded-tl-[15px] rounded-tr-[15px] shadow-custom h-[98vh] w-full bg-bricks-green">
`

2024-09-24 04:37 UTC, edzhabs commented on frontend/src/components/Dashboard/index.tsx
> +        <div className="flex flex-col items-center w-full h-screen pt-4 pr-4 pb-4 pl-4 gap-4 bg-[#f4f4f4]"></div>
also the color here `bg-[#f4f4f4]`

2024-09-24 04:37 UTC, edzhabs commented on frontend/src/shared/components/Footer/index.tsx
> +    <footer className=" text-[#f4f4f4] py-4">
also the color here `text-[#f4f4f4]`

2024-09-25 14:30 UTC, merged