Feat/fe sign in
Biniverse/server-test pull request #48
Opened 2024-09-27 01:35 UTC by 22tofu

## Description

Add Sign In functionality

## Checklist

_First, create a draft pull request. Then mark the PR as ready for review when all necessary checkbox items has been completed_

- [ ] Reviewed own code
- [ ] Commented on code that is hard to understand
- [ ] Implemented tests for the feature/bugfix
- [ ] All **_Required_** GitHub status checks pass
- [ ] The frontend and backend PR previews have been deployed

2024-09-27 01:40 UTC, 22tofu commented
Please don't hesitate to correct my work as I am still learning and willing to learn
Note: Advise and suggestions are open

2024-09-27 02:13 UTC, beefysalad requested changes
Looks good but some minor changes are required

2024-09-27 02:13 UTC, beefysalad commented on frontend/src/service/Sign-In/signInService.ts
> +  const response = await fetch("/users-list", {
while using fetch api from js is correct, maybe you can also utilize the httpService provider that i created inside the  service folder. For reference:
![image](https://github.com/user-attachments/assets/4df808a9-c62f-4075-8bf8-f56e04331050)
To use it on your service:
![image](https://github.com/user-attachments/assets/52115637-af1a-47db-b672-329e858ec2e9)
Simply call http + the http method (post, get, delete,  patch) etc etc.

2024-09-27 02:13 UTC, beefysalad commented on frontend/src/service/Sign-In/signInService.ts
> +  const response = await fetch("/users-list", {
Also the endpoint `/users-list` is an endpoint used to get all users which will be displayed on a table. This is not the actual login endpoint. On going pa si boss stephen sa endpoint for login

2024-09-27 02:13 UTC, beefysalad commented on frontend/src/components/SignIn/index.tsx
> +  const [username, setUsername] = useState("");
since we are using typescript, we should always put types. 
i.e. 
```javascript
useState<string>(""); //if string is the expected output of the variable
useState<number>(0); //if number is the expected output of the variable
useState<CustomType>({}) //if you have some custom types
```

in this case username and password should have a string type.
```javascript
const [username,setUsername] = useState<string>("");
const [password,setPassword] = useState<string>(""); 
```

2024-09-27 03:01 UTC, edzhabs requested changes
minor changes

2024-09-27 03:01 UTC, edzhabs commented on frontend/src/components/SignIn/index.tsx
> +            <img
all `img` are using the same class and repetitive, can this be stored in  array and map the `src` of images? So that we do not need to change all class of all `img` elements if we need to change or add some styles.

2024-09-27 03:01 UTC, edzhabs commented on frontend/src/components/SignIn/index.tsx
> +            <img
Can we apply lazy-loading on images for optimization? this is the package. [Lazy-Loading](https://discord.com/channels/1286612014374060034/1286663084924211221/1288518166917677201)

2024-09-27 05:06 UTC, jefoneg commented on frontend/src/components/SignIn/index.tsx
> +      console.log("Signed in successfully:", data);
please remove this console log

2024-09-27 05:06 UTC, jefoneg commented on frontend/src/components/SignIn/index.tsx
> +            Good Evening!
Please add this magic string to the `commonConstant` file.

2024-09-27 05:06 UTC, jefoneg commented on frontend/src/components/SignIn/index.tsx
> +                Forgot Password?
Please add this magic string to the `commonConstant` file.

2024-09-27 05:06 UTC, jefoneg commented on frontend/src/components/SignIn/index.tsx
> +                Login
Please add this magic string to the `commonConstant` file.

2024-09-27 05:06 UTC, jefoneg commented on frontend/src/service/Sign-In/signInService.ts
> +    throw new Error("Invalid Credentials");
Please add this magic string to the `commonConstant` file.

2024-09-27 14:23 UTC, edzhabs commented
naa nani validations like if incorrect password? pwede ra guro mo use [react-hook-forms](https://www.react-hook-form.com/) or [tanstack](https://tanstack.com/)

2024-09-29 07:08 UTC, beefysalad commented
> naa nani validations like if incorrect password? pwede ra guro mo use [react-hook-forms](https://www.react-hook-form.com/) or [tanstack](https://tanstack.com/)

Pwede ta mugami sa react-hook-forms, naka install nani sa latest dev since gigamit nako sa FE signup.
cc: @Biniverse/bini

2024-10-03 02:37 UTC, closed without merging